import json

def code(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

cells = []

# ── TITLE ──────────────────────────────────────────────────────────────────
cells.append(md(
    "# Liverpool Energy Performance Certificate Analysis\n"
    "## COM6003 Data Science — Buckinghamshire New University 2025-26\n\n"
    "**Dataset:** Energy Performance of Buildings — Liverpool (Local Authority: E08000012)  \n"
    "**Source:** Ministry of Housing, Communities and Local Government (MHCLG) Open Data Portal  \n"
    "**Assessment method:** Standard Assessment Procedure (SAP) and Reduced SAP (RdSAP)  \n\n"
    "This notebook presents a complete end-to-end data science pipeline covering data acquisition, "
    "feature engineering, data wrangling, descriptive analytics, diagnostic analytics, "
    "predictive modelling, and recommendations for improving energy efficiency in Liverpool buildings."
))

# ── SECTION 1 ──────────────────────────────────────────────────────────────
cells.append(md("## Section 1: Data Acquisition and Understanding"))

# Imports + load
cells.append(code(
    "import pandas as pd\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.patches as mpatches\n"
    "import seaborn as sns\n"
    "from sklearn.model_selection import train_test_split, cross_val_score\n"
    "from sklearn.preprocessing import LabelEncoder, StandardScaler\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n"
    "from sklearn.metrics import (accuracy_score, f1_score, confusion_matrix,\n"
    "                              classification_report, ConfusionMatrixDisplay)\n"
    "from sklearn.inspection import permutation_importance\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n\n"
    "# Global style\n"
    "plt.rcParams['font.family'] = 'DejaVu Sans'\n"
    "plt.rcParams['axes.titlesize'] = 14\n"
    "plt.rcParams['axes.titleweight'] = 'bold'\n"
    "plt.rcParams['axes.labelsize'] = 11\n"
    "plt.rcParams['xtick.labelsize'] = 10\n"
    "plt.rcParams['ytick.labelsize'] = 10\n"
    "sns.set_theme(style='whitegrid', palette='muted')\n\n"
    "# Consistent colour palettes used throughout\n"
    "RATING_COLORS  = {'A': '#2ecc71', 'B': '#27ae60', 'C': '#f1c40f',\n"
    "                   'D': '#e67e22', 'E': '#e74c3c'}\n"
    "AGE_COLORS     = ['#8e44ad','#2980b9','#27ae60','#f39c12',\n"
    "                   '#e67e22','#e74c3c','#1abc9c']\n"
    "PALETTE        = ['#3498db','#e74c3c','#2ecc71','#f39c12','#9b59b6']\n"
    "EFF_COLORS     = ['#2ecc71','#27ae60','#f1c40f','#e67e22','#e74c3c']\n"
    "AGE_ORDER      = ['Pre-1900','1900-1949','1950-1975','1976-1990',\n"
    "                   '1991-2002','2003-2021','Post-2021']\n"
    "EFF_ORDER      = ['Very Good','Good','Average','Poor','Very Poor']\n\n"
    "# Helper: annotate bars with count and optional percentage\n"
    "def bar_labels(ax, bars, values, total=None, fmt=',.0f',\n"
    "               offset_pct=0.015, fontsize=9.5, color='black'):\n"
    "    ylim = ax.get_ylim()\n"
    "    span = ylim[1] - ylim[0]\n"
    "    for bar, val in zip(bars, values):\n"
    "        label = f'{val:{fmt}}'\n"
    "        if total:\n"
    "            label += f'\\n({val / total * 100:.1f}%)'\n"
    "        ax.text(bar.get_x() + bar.get_width() / 2,\n"
    "                bar.get_height() + span * offset_pct,\n"
    "                label, ha='center', va='bottom',\n"
    "                fontsize=fontsize, fontweight='bold', color=color)\n\n"
    "# Helper: annotate horizontal bars\n"
    "def hbar_labels(ax, bars, values, offset_pct=0.01, fontsize=9.5):\n"
    "    xlim = ax.get_xlim()\n"
    "    span = xlim[1] - xlim[0]\n"
    "    for bar, val in zip(bars, values):\n"
    "        ax.text(val + span * offset_pct,\n"
    "                bar.get_y() + bar.get_height() / 2,\n"
    "                f'{val:.1f}', va='center',\n"
    "                fontsize=fontsize, fontweight='bold')\n\n"
    "df   = pd.read_csv('certificates.csv', low_memory=False)\n"
    "recs = pd.read_csv('recommendations.csv', low_memory=False)\n\n"
    "print(f'Certificates  : {df.shape[0]:,} rows, {df.shape[1]} columns')\n"
    "print(f'Recommendations: {recs.shape[0]:,} rows, {recs.shape[1]} columns')\n"
    "print(f'Local authority: {df[\"LOCAL_AUTHORITY_LABEL\"].unique()}')\n"
    "print(f'Inspection dates: {df[\"INSPECTION_DATE\"].min()}  to  {df[\"INSPECTION_DATE\"].max()}')"
))

# 1.1 Dataset overview
cells.append(md("### 1.1 Dataset Overview"))
cells.append(code(
    "print('Shape:', df.shape)\n"
    "print()\n"
    "print('Column data types:')\n"
    "print(df.dtypes.value_counts())\n"
    "print()\n"
    "print('First 3 rows (selected columns):')\n"
    "preview_cols = ['CURRENT_ENERGY_RATING','CURRENT_ENERGY_EFFICIENCY','PROPERTY_TYPE',\n"
    "                'CONSTRUCTION_AGE_BAND','TENURE','TOTAL_FLOOR_AREA',\n"
    "                'CO2_EMISSIONS_CURRENT','HEATING_COST_CURRENT']\n"
    "display(df[preview_cols].head(3))"
))

# 1.2 Missing values
cells.append(md("### 1.2 Missing Values Analysis"))
cells.append(code(
    "missing     = df.isnull().sum()\n"
    "missing_pct = (missing / len(df) * 100).round(2)\n"
    "missing_df  = pd.DataFrame({'Missing Count': missing,\n"
    "                             'Missing %': missing_pct})\n"
    "missing_df  = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False)\n\n"
    "print(f'Columns with missing values : {len(missing_df)} of {df.shape[1]}')\n"
    "print(f'Columns fully populated     : {df.shape[1] - len(missing_df)}')\n"
    "print()\n"
    "display(missing_df.style\n"
    "        .background_gradient(subset=['Missing %'], cmap='Reds')\n"
    "        .format({'Missing %': '{:.2f}%'}))\n\n"
    "# Visualise missing values\n"
    "fig, ax = plt.subplots(figsize=(13, 7))\n"
    "missing_plot = missing_df[missing_df['Missing %'] > 0].sort_values('Missing %')\n"
    "colors_miss  = ['#e74c3c' if v == 100 else '#e67e22' if v > 50 else '#f1c40f'\n"
    "                for v in missing_plot['Missing %']]\n"
    "bars = ax.barh(missing_plot.index, missing_plot['Missing %'],\n"
    "               color=colors_miss, edgecolor='white', linewidth=0.5)\n"
    "for bar, val in zip(bars, missing_plot['Missing %']):\n"
    "    ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,\n"
    "            f'{val:.1f}%', va='center', fontsize=9, fontweight='bold')\n"
    "ax.axvline(50, color='red', linestyle='--', linewidth=1.2,\n"
    "           label='50% threshold (drop limit)')\n"
    "ax.axvline(100, color='black', linestyle='--', linewidth=1.2,\n"
    "           label='100% missing (auto-drop)')\n"
    "ax.set_xlabel('Missing Value Percentage (%)')\n"
    "ax.set_title('Missing Values by Column — Liverpool EPC Dataset', pad=15)\n"
    "legend_patches = [\n"
    "    mpatches.Patch(color='#e74c3c', label='100% missing (drop all)'),\n"
    "    mpatches.Patch(color='#e67e22', label='>50% missing (drop)'),\n"
    "    mpatches.Patch(color='#f1c40f', label='<50% missing (impute)'),\n"
    "]\n"
    "ax.legend(handles=legend_patches, loc='lower right', fontsize=9)\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart0_missing_values.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()"
))

# 1.3 Duplicates
cells.append(md("### 1.3 Duplicate Records"))
cells.append(code(
    "total_dups = df.duplicated().sum()\n"
    "lmk_dups   = df.duplicated(subset=['LMK_KEY']).sum()\n"
    "print(f'Fully duplicate rows    : {total_dups}')\n"
    "print(f'Duplicate LMK_KEY values: {lmk_dups}')\n"
    "if total_dups > 0:\n"
    "    df = df.drop_duplicates()\n"
    "    print(f'Removed {total_dups} rows. Remaining: {len(df):,}')\n"
    "else:\n"
    "    print('No duplicate rows found. Each certificate is unique.')"
))

# 1.4 Target and stats
cells.append(md("### 1.4 Target Variable and Key Statistics"))
cells.append(code(
    "rating_counts  = df['CURRENT_ENERGY_RATING'].value_counts().sort_index()\n"
    "rating_pct     = (rating_counts / len(df) * 100).round(1)\n"
    "rating_summary = pd.DataFrame({'Count': rating_counts, 'Percentage (%)': rating_pct})\n"
    "rating_summary['Cumulative %'] = rating_pct.cumsum().round(1)\n"
    "print('Target variable: CURRENT_ENERGY_RATING')\n"
    "display(rating_summary)\n"
    "print()\n"
    "key_cols = ['CURRENT_ENERGY_EFFICIENCY','POTENTIAL_ENERGY_EFFICIENCY',\n"
    "            'TOTAL_FLOOR_AREA','CO2_EMISSIONS_CURRENT',\n"
    "            'ENERGY_CONSUMPTION_CURRENT','HEATING_COST_CURRENT',\n"
    "            'HOT_WATER_COST_CURRENT','LIGHTING_COST_CURRENT']\n"
    "print('Summary statistics — key numerical features:')\n"
    "display(df[key_cols].describe().round(2)\n"
    "        .style.background_gradient(cmap='Blues', subset=pd.IndexSlice['mean':'max', :]))"
))

cells.append(code(
    "print('Key categorical features:')\n"
    "print()\n"
    "for col in ['PROPERTY_TYPE','BUILT_FORM','TENURE','CONSTRUCTION_AGE_BAND',\n"
    "            'TRANSACTION_TYPE','MAIN_FUEL']:\n"
    "    counts = df[col].value_counts()\n"
    "    pcts   = (counts / len(df) * 100).round(1)\n"
    "    tbl    = pd.DataFrame({'Count': counts, '%': pcts})\n"
    "    print(f'{col}:')\n"
    "    display(tbl)\n"
    "    print()"
))

# 1.5 Methodology note
cells.append(md(
    "### 1.5 Data Collection Methodology and Limitations\n\n"
    "EPCs are produced using the **Reduced Standard Assessment Procedure (RdSAP)** for existing "
    "dwellings and full SAP for new builds. Assessors physically inspect properties and record "
    "building fabric, heating systems, insulation, glazing, and fuel types.\n\n"
    "**Potential biases and limitations:**\n"
    "- EPCs are only required when a property is sold, let, or newly built — the dataset does not "
    "represent the full Liverpool housing stock, only transacted properties.\n"
    "- RdSAP uses assumed values for some features (e.g., insulation inferred from construction age) "
    "rather than direct measurement, introducing estimation error.\n"
    "- Assessor subjectivity can produce inconsistent ratings for similar properties.\n"
    "- The dataset contains 5,000 records — a sample rather than the complete Liverpool register.\n"
    "- Properties assessed under different SAP versions (REPORT_TYPE 100=RdSAP vs 101=SAP) may "
    "not be directly comparable."
))

# ── SECTION 2: FEATURE ENGINEERING ─────────────────────────────────────────
cells.append(md(
    "## Section 2: Feature Engineering\n\n"
    "Before cleaning, uninformative columns are removed and seven new features are created from "
    "existing data. Engineering at this stage ensures the derived features are processed through "
    "the same wrangling pipeline as the original columns."
))

cells.append(code(
    "# Remove 100% missing columns\n"
    "cols_100 = [c for c in df.columns if df[c].isnull().sum() == len(df)]\n"
    "print(f'Columns with 100% missing values ({len(cols_100)} dropped):')\n"
    "for c in cols_100:\n"
    "    print(f'  {c}')\n"
    "df = df.drop(columns=cols_100)\n\n"
    "# Remove identifier and address columns\n"
    "id_cols = ['LMK_KEY','ADDRESS1','ADDRESS2','ADDRESS3','POSTCODE',\n"
    "           'BUILDING_REFERENCE_NUMBER','ADDRESS','UPRN','UPRN_SOURCE',\n"
    "           'LOCAL_AUTHORITY','CONSTITUENCY','POSTTOWN','LOCAL_AUTHORITY_LABEL']\n"
    "id_cols = [c for c in id_cols if c in df.columns]\n"
    "df = df.drop(columns=id_cols)\n"
    "print(f'\\nIdentifier columns dropped: {len(id_cols)}')\n"
    "print(f'Remaining columns         : {df.shape[1]}')"
))

cells.append(md("### 2.1 New Feature Definitions"))
cells.append(code(
    "# 1. Numeric rating for correlation analysis (A=7 … G=1)\n"
    "#    Not used as a model feature — would be direct leakage of the target\n"
    "rating_map = {'A':7,'B':6,'C':5,'D':4,'E':3,'F':2,'G':1}\n"
    "df['ENERGY_RATING_NUMERIC'] = df['CURRENT_ENERGY_RATING'].map(rating_map)\n\n"
    "# 2. Efficiency gap: headroom for improvement per property\n"
    "df['EFFICIENCY_GAP'] = df['POTENTIAL_ENERGY_EFFICIENCY'] - df['CURRENT_ENERGY_EFFICIENCY']\n\n"
    "# 3. Total annual energy costs\n"
    "df['TOTAL_COST_CURRENT']   = (df['HEATING_COST_CURRENT'] +\n"
    "                               df['HOT_WATER_COST_CURRENT'] +\n"
    "                               df['LIGHTING_COST_CURRENT'])\n"
    "df['TOTAL_COST_POTENTIAL'] = (df['HEATING_COST_POTENTIAL'] +\n"
    "                               df['HOT_WATER_COST_POTENTIAL'] +\n"
    "                               df['LIGHTING_COST_POTENTIAL'])\n\n"
    "# 4. Annual saving if all EPC recommendations were implemented\n"
    "#    Clipped at 0: rare negative values indicate community-scheme properties\n"
    "#    where potential costs exceed current costs — not modelling errors\n"
    "df['COST_SAVING_POTENTIAL'] = (df['TOTAL_COST_CURRENT'] -\n"
    "                                df['TOTAL_COST_POTENTIAL']).clip(lower=0)\n\n"
    "# 5. CO2 intensity normalised by floor area\n"
    "df['CO2_PER_AREA'] = (df['CO2_EMISSIONS_CURRENT'] /\n"
    "                       df['TOTAL_FLOOR_AREA'].replace(0, np.nan)).round(4)\n\n"
    "# 6. Simplified age band — groups the 17 raw CONSTRUCTION_AGE_BAND values\n"
    "#    into 7 meaningful periods aligned with major UK building regulation changes\n"
    "def classify_age(val):\n"
    "    if pd.isnull(val):\n"
    "        return 'Unknown'\n"
    "    val = str(val)\n"
    "    if 'before 1900' in val:\n"
    "        return 'Pre-1900'\n"
    "    elif '1900-1929' in val or '1930-1949' in val:\n"
    "        return '1900-1949'\n"
    "    elif '1950-1966' in val or '1967-1975' in val:\n"
    "        return '1950-1975'\n"
    "    elif '1976-1982' in val or '1983-1990' in val:\n"
    "        return '1976-1990'\n"
    "    elif '1991-1995' in val or '1996-2002' in val:\n"
    "        return '1991-2002'\n"
    "    elif ('2003-2006' in val or '2007-2011' in val or\n"
    "          '2012-2021' in val or val.strip() == '2020'):\n"
    "        return '2003-2021'\n"
    "    else:\n"
    "        return 'Post-2021'\n\n"
    "df['PROPERTY_AGE_GROUP'] = df['CONSTRUCTION_AGE_BAND'].apply(classify_age)\n\n"
    "# 7. Cleaned tenure labels\n"
    "tenure_map = {'Rented (social)': 'Social Rented',\n"
    "              'Owner-occupied':   'Owner-occupied',\n"
    "              'Rented (private)': 'Private Rented'}\n"
    "df['TENURE_CLEAN'] = df['TENURE'].map(tenure_map).fillna('Other')\n\n"
    "new_feats = ['ENERGY_RATING_NUMERIC','EFFICIENCY_GAP','TOTAL_COST_CURRENT',\n"
    "             'TOTAL_COST_POTENTIAL','COST_SAVING_POTENTIAL','CO2_PER_AREA',\n"
    "             'PROPERTY_AGE_GROUP','TENURE_CLEAN']\n"
    "print(f'New features created: {len(new_feats)}')\n"
    "print(f'Total columns: {df.shape[1]}')\n"
    "print()\n"
    "print('Sample values for engineered features:')\n"
    "display(df[new_feats].head(5))\n"
    "print()\n"
    "print('Efficiency Gap (points of improvement available):')\n"
    "display(df['EFFICIENCY_GAP'].describe().round(2).to_frame().T)\n"
    "print()\n"
    "print('Cost Saving Potential (GBP/year):')\n"
    "display(df['COST_SAVING_POTENTIAL'].describe().round(2).to_frame().T)"
))

# ── SECTION 3: DATA WRANGLING ───────────────────────────────────────────────
cells.append(md(
    "## Section 3: Data Wrangling (Analysis 3.1)\n\n"
    "The pipeline addresses four quality issues: high-missingness columns, "
    "remaining missing values, extreme outliers, and incorrect data types. "
    "Derived cost features are recalculated after outlier removal to remain consistent."
))

cells.append(code(
    "print('Step 1 — Drop columns with more than 50% missing values')\n"
    "print()\n"
    "mp        = (df.isnull().sum() / len(df)) * 100\n"
    "drop50    = mp[mp > 50].index.tolist()\n"
    "drop_info = pd.DataFrame({'Column': drop50,\n"
    "                           'Missing %': [round(mp[c], 1) for c in drop50]})\n"
    "display(drop_info.sort_values('Missing %', ascending=False).reset_index(drop=True))\n"
    "df = df.drop(columns=drop50)\n"
    "print(f'Dropped {len(drop50)} columns  |  Remaining: {df.shape[1]} columns, {df.shape[0]:,} rows')"
))

cells.append(code(
    "print('Step 2 — Impute remaining missing values')\n"
    "print()\n"
    "still = df.isnull().sum()\n"
    "still = still[still > 0].sort_values(ascending=False)\n"
    "print(f'Columns still with missing values: {len(still)}')\n"
    "display(pd.DataFrame({'Column': still.index, 'Missing Count': still.values,\n"
    "                       'Missing %': (still.values / len(df) * 100).round(2)}))\n"
    "print()\n"
    "for col in df.select_dtypes(include=['float64','int64']).columns:\n"
    "    if df[col].isnull().sum() > 0:\n"
    "        med = df[col].median()\n"
    "        df[col] = df[col].fillna(med)\n"
    "        print(f'  {col}: filled with median ({med:.2f})')\n"
    "for col in df.select_dtypes(include='object').columns:\n"
    "    if df[col].isnull().sum() > 0:\n"
    "        mod = df[col].mode()[0]\n"
    "        df[col] = df[col].fillna(mod)\n"
    "        print(f'  {col}: filled with mode (\"{mod}\")')\n"
    "print(f'\\nMissing values remaining: {df.isnull().sum().sum()}')"
))

cells.append(md("### 3.1 Outlier Detection and Removal"))
cells.append(code(
    "rows_before = len(df)\n"
    "outlier_cols = ['CURRENT_ENERGY_EFFICIENCY','TOTAL_FLOOR_AREA',\n"
    "                'CO2_EMISSIONS_CURRENT','ENERGY_CONSUMPTION_CURRENT',\n"
    "                'HEATING_COST_CURRENT','TOTAL_COST_CURRENT']\n\n"
    "report = []\n"
    "for col in outlier_cols:\n"
    "    Q1  = df[col].quantile(0.25)\n"
    "    Q3  = df[col].quantile(0.75)\n"
    "    IQR = Q3 - Q1\n"
    "    lo  = Q1 - 1.5 * IQR\n"
    "    hi  = Q3 + 1.5 * IQR\n"
    "    n   = df[(df[col] < lo) | (df[col] > hi)].shape[0]\n"
    "    report.append({'Column': col, 'Q1': round(Q1,2), 'Q3': round(Q3,2),\n"
    "                   'Lower Fence': round(lo,2), 'Upper Fence': round(hi,2),\n"
    "                   'Outliers': n})\n"
    "display(pd.DataFrame(report))\n\n"
    "for col in ['TOTAL_FLOOR_AREA','HEATING_COST_CURRENT','TOTAL_COST_CURRENT']:\n"
    "    Q1 = df[col].quantile(0.25); Q3 = df[col].quantile(0.75); IQR = Q3 - Q1\n"
    "    df = df[(df[col] >= Q1-1.5*IQR) & (df[col] <= Q3+1.5*IQR)]\n\n"
    "# Recalculate cost features after outlier removal\n"
    "df['TOTAL_COST_CURRENT']    = (df['HEATING_COST_CURRENT'] +\n"
    "                                df['HOT_WATER_COST_CURRENT'] +\n"
    "                                df['LIGHTING_COST_CURRENT'])\n"
    "df['TOTAL_COST_POTENTIAL']  = (df['HEATING_COST_POTENTIAL'] +\n"
    "                                df['HOT_WATER_COST_POTENTIAL'] +\n"
    "                                df['LIGHTING_COST_POTENTIAL'])\n"
    "df['COST_SAVING_POTENTIAL'] = (df['TOTAL_COST_CURRENT'] -\n"
    "                                df['TOTAL_COST_POTENTIAL']).clip(lower=0)\n\n"
    "print(f'Rows before: {rows_before:,}  |  Rows after: {len(df):,}  |  Removed: {rows_before-len(df):,}')"
))

cells.append(code(
    "df['INSPECTION_DATE']    = pd.to_datetime(df['INSPECTION_DATE'],    errors='coerce')\n"
    "df['LODGEMENT_DATE']     = pd.to_datetime(df['LODGEMENT_DATE'],     errors='coerce')\n"
    "df['LODGEMENT_DATETIME'] = pd.to_datetime(df['LODGEMENT_DATETIME'], errors='coerce')\n"
    "df['INSPECTION_YEAR']    = df['INSPECTION_DATE'].dt.year.fillna(0).astype(int)\n\n"
    "print('Cleaned dataset summary:')\n"
    "summary = pd.DataFrame({\n"
    "    'Metric': ['Rows','Columns','Missing values','Negative cost savings','Unique energy ratings'],\n"
    "    'Value':  [f'{df.shape[0]:,}', df.shape[1],\n"
    "               df.isnull().sum().sum(),\n"
    "               (df['COST_SAVING_POTENTIAL'] < 0).sum(),\n"
    "               df['CURRENT_ENERGY_RATING'].nunique()]\n"
    "})\n"
    "display(summary)\n"
    "print()\n"
    "print('Energy rating distribution after cleaning:')\n"
    "rc = df['CURRENT_ENERGY_RATING'].value_counts().sort_index()\n"
    "display(pd.DataFrame({'Count': rc, '%': (rc/len(df)*100).round(1)}))\n\n"
    "df.to_csv('liverpool_epc_cleaned.csv', index=False)\n"
    "print('\\nCleaned dataset saved: liverpool_epc_cleaned.csv')"
))

# ── SECTION 4: DESCRIPTIVE ANALYTICS ───────────────────────────────────────
cells.append(md(
    "## Section 4: Descriptive Analytics (Analysis 3.2)\n\n"
    "Descriptive analytics answers **'What has occurred?'** by summarising the distribution of "
    "energy ratings, property characteristics, tenure patterns, and cost profiles "
    "across 4,579 properties in the cleaned Liverpool EPC dataset."
))

cells.append(code(
    "key_num = ['CURRENT_ENERGY_EFFICIENCY','POTENTIAL_ENERGY_EFFICIENCY',\n"
    "           'TOTAL_FLOOR_AREA','CO2_EMISSIONS_CURRENT','HEATING_COST_CURRENT',\n"
    "           'TOTAL_COST_CURRENT','EFFICIENCY_GAP','COST_SAVING_POTENTIAL']\n"
    "print('Summary statistics — key numerical features (cleaned dataset):')\n"
    "display(df[key_num].describe().round(2)\n"
    "        .style.background_gradient(cmap='YlOrRd', subset=pd.IndexSlice[['mean','std'], :])\n"
    "        .format('{:.2f}'))"
))

# Chart 1
cells.append(md("### Chart 1: Energy Rating Distribution"))
cells.append(code(
    "rating_counts = df['CURRENT_ENERGY_RATING'].value_counts().sort_index()\n"
    "total         = len(df)\n"
    "r_colors      = [RATING_COLORS.get(r, '#888') for r in rating_counts.index]\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "# Bar chart\n"
    "bars = axes[0].bar(rating_counts.index, rating_counts.values,\n"
    "                    color=r_colors, edgecolor='white', linewidth=1.2, width=0.65)\n"
    "bar_labels(axes[0], bars, rating_counts.values, total=total, fontsize=10)\n"
    "axes[0].set_title('Energy Rating Distribution — Liverpool EPC (n=4,579)', pad=15)\n"
    "axes[0].set_xlabel('Energy Rating Band')\n"
    "axes[0].set_ylabel('Number of Properties')\n"
    "axes[0].set_ylim(0, rating_counts.max() * 1.22)\n"
    "axes[0].grid(axis='y', alpha=0.4)\n"
    "axes[0].set_axisbelow(True)\n\n"
    "# Pie chart with count + percentage labels\n"
    "def autopct_with_count(pct, allvals):\n"
    "    n = int(round(pct / 100 * sum(allvals)))\n"
    "    return f'{pct:.1f}%\\n({n:,})'\n\n"
    "wedges, texts, autotexts = axes[1].pie(\n"
    "    rating_counts.values,\n"
    "    labels=rating_counts.index,\n"
    "    colors=r_colors,\n"
    "    autopct=lambda p: autopct_with_count(p, rating_counts.values),\n"
    "    startangle=90, pctdistance=0.72,\n"
    "    wedgeprops={'edgecolor': 'white', 'linewidth': 1.5})\n"
    "for t in texts:     t.set_fontsize(12); t.set_fontweight('bold')\n"
    "for at in autotexts: at.set_fontsize(9)\n"
    "axes[1].set_title('Energy Rating Share — Count and Percentage', pad=15)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart1_energy_rating_distribution.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: 68.6% of properties are rated C. Fewer than 2% achieved A or B.')"
))

# Chart 2
cells.append(md("### Chart 2: Property Type Distribution and Efficiency"))
cells.append(code(
    "prop_counts = df['PROPERTY_TYPE'].value_counts()\n"
    "avg_eff     = df.groupby('PROPERTY_TYPE')['CURRENT_ENERGY_EFFICIENCY'].mean().loc[prop_counts.index]\n"
    "total       = len(df)\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "bars1 = axes[0].bar(prop_counts.index, prop_counts.values,\n"
    "                     color=PALETTE[:len(prop_counts)],\n"
    "                     edgecolor='white', linewidth=1.2, width=0.6)\n"
    "bar_labels(axes[0], bars1, prop_counts.values, total=total, fontsize=10)\n"
    "axes[0].set_title('Property Type Distribution (n=4,579)', pad=15)\n"
    "axes[0].set_xlabel('Property Type')\n"
    "axes[0].set_ylabel('Number of Properties')\n"
    "axes[0].set_ylim(0, prop_counts.max() * 1.22)\n"
    "axes[0].grid(axis='y', alpha=0.4); axes[0].set_axisbelow(True)\n\n"
    "bars2 = axes[1].bar(avg_eff.index, avg_eff.values,\n"
    "                     color=PALETTE[:len(avg_eff)],\n"
    "                     edgecolor='white', linewidth=1.2, width=0.6)\n"
    "axes[1].set_ylim(0, avg_eff.max() * 1.18)\n"
    "for bar, val in zip(bars2, avg_eff.values):\n"
    "    axes[1].text(bar.get_x() + bar.get_width()/2,\n"
    "                 bar.get_height() + 0.6,\n"
    "                 f'{val:.1f}', ha='center', fontsize=10.5, fontweight='bold')\n"
    "axes[1].set_title('Average Energy Efficiency Score by Property Type', pad=15)\n"
    "axes[1].set_xlabel('Property Type')\n"
    "axes[1].set_ylabel('Average Efficiency Score')\n"
    "axes[1].axhline(df['CURRENT_ENERGY_EFFICIENCY'].mean(), color='red',\n"
    "                linestyle='--', linewidth=1.5,\n"
    "                label=f'Overall mean: {df[\"CURRENT_ENERGY_EFFICIENCY\"].mean():.1f}')\n"
    "axes[1].legend(fontsize=9)\n"
    "axes[1].grid(axis='y', alpha=0.4); axes[1].set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart2_property_type.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: Houses (63.7%) dominate Liverpool stock. Maisonettes score highest')\n"
    "print('on efficiency (75.4) while Houses and Bungalows sit slightly below average.')"
))

# Chart 3
cells.append(md("### Chart 3: Construction Age Band"))
cells.append(code(
    "age_counts  = df['PROPERTY_AGE_GROUP'].value_counts().reindex(AGE_ORDER).dropna()\n"
    "avg_eff_age = df.groupby('PROPERTY_AGE_GROUP')['CURRENT_ENERGY_EFFICIENCY'].mean().reindex(AGE_ORDER).dropna()\n"
    "total       = len(df)\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "bars3 = axes[0].bar(range(len(age_counts)), age_counts.values,\n"
    "                     color=AGE_COLORS[:len(age_counts)],\n"
    "                     edgecolor='white', linewidth=1.2, width=0.65)\n"
    "bar_labels(axes[0], bars3, age_counts.values, total=total, fontsize=9)\n"
    "axes[0].set_xticks(range(len(age_counts)))\n"
    "axes[0].set_xticklabels(age_counts.index, rotation=30, ha='right', fontsize=9.5)\n"
    "axes[0].set_title('Properties by Construction Age Group (n=4,579)', pad=15)\n"
    "axes[0].set_xlabel('Age Group')\n"
    "axes[0].set_ylabel('Number of Properties')\n"
    "axes[0].set_ylim(0, age_counts.max() * 1.22)\n"
    "axes[0].grid(axis='y', alpha=0.4); axes[0].set_axisbelow(True)\n\n"
    "bars4 = axes[1].bar(range(len(avg_eff_age)), avg_eff_age.values,\n"
    "                     color=AGE_COLORS[:len(avg_eff_age)],\n"
    "                     edgecolor='white', linewidth=1.2, width=0.65)\n"
    "axes[1].plot(range(len(avg_eff_age)), avg_eff_age.values,\n"
    "             'o-', color='#2c3e50', linewidth=2, markersize=6, zorder=5,\n"
    "             label='Trend')\n"
    "for i, val in enumerate(avg_eff_age.values):\n"
    "    axes[1].text(i, val + 0.25, f'{val:.1f}',\n"
    "                 ha='center', fontsize=9.5, fontweight='bold')\n"
    "axes[1].set_xticks(range(len(avg_eff_age)))\n"
    "axes[1].set_xticklabels(avg_eff_age.index, rotation=30, ha='right', fontsize=9.5)\n"
    "axes[1].set_ylim(65, 82)\n"
    "axes[1].axhline(df['CURRENT_ENERGY_EFFICIENCY'].mean(), color='red',\n"
    "                linestyle='--', linewidth=1.4,\n"
    "                label=f'Overall mean: {df[\"CURRENT_ENERGY_EFFICIENCY\"].mean():.1f}')\n"
    "axes[1].legend(fontsize=9)\n"
    "axes[1].set_title('Average Efficiency Score by Construction Age', pad=15)\n"
    "axes[1].set_xlabel('Age Group')\n"
    "axes[1].set_ylabel('Average Efficiency Score')\n"
    "axes[1].grid(axis='y', alpha=0.4); axes[1].set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart3_age_band.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: 44.1% of properties built 1900-1949. Clear upward efficiency trend')\n"
    "print('from Pre-1900 (69.5) to Post-2021 (78.6) — a 9.1 point improvement.')"
))

# Chart 4
cells.append(md("### Chart 4: Efficiency and Floor Area Box Plots"))
cells.append(code(
    "rating_order = ['A','B','C','D','E']\n"
    "df_rated     = df[df['CURRENT_ENERGY_RATING'].isin(rating_order)]\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "bp = sns.boxplot(data=df_rated, x='CURRENT_ENERGY_RATING',\n"
    "                  y='CURRENT_ENERGY_EFFICIENCY',\n"
    "                  order=rating_order,\n"
    "                  palette=[RATING_COLORS[r] for r in rating_order],\n"
    "                  ax=axes[0], linewidth=1.2, fliersize=3)\n"
    "# Add median labels and sample size\n"
    "for i, rating in enumerate(rating_order):\n"
    "    subset = df_rated[df_rated['CURRENT_ENERGY_RATING'] == rating]['CURRENT_ENERGY_EFFICIENCY']\n"
    "    med    = subset.median()\n"
    "    n      = len(subset)\n"
    "    axes[0].text(i, med + 0.8, f'{med:.0f}',\n"
    "                 ha='center', fontsize=9, fontweight='bold', color='black')\n"
    "    axes[0].text(i, axes[0].get_ylim()[0] + 1.5, f'n={n:,}',\n"
    "                 ha='center', fontsize=8, color='#555')\n"
    "axes[0].set_title('Efficiency Score Distribution by Rating Band', pad=15)\n"
    "axes[0].set_xlabel('Energy Rating')\n"
    "axes[0].set_ylabel('Energy Efficiency Score')\n"
    "axes[0].grid(axis='y', alpha=0.4)\n\n"
    "sns.boxplot(data=df, x='PROPERTY_TYPE', y='TOTAL_FLOOR_AREA',\n"
    "            palette=PALETTE, ax=axes[1], linewidth=1.2, fliersize=3)\n"
    "for i, ptype in enumerate(df['PROPERTY_TYPE'].value_counts().index):\n"
    "    subset = df[df['PROPERTY_TYPE'] == ptype]['TOTAL_FLOOR_AREA']\n"
    "    med    = subset.median()\n"
    "    n      = len(subset)\n"
    "    axes[1].text(i, med + 0.8, f'{med:.0f}m²',\n"
    "                 ha='center', fontsize=9, fontweight='bold')\n"
    "    axes[1].text(i, axes[1].get_ylim()[0] + 0.8, f'n={n:,}',\n"
    "                 ha='center', fontsize=8, color='#555')\n"
    "axes[1].set_title('Floor Area Distribution by Property Type', pad=15)\n"
    "axes[1].set_xlabel('Property Type')\n"
    "axes[1].set_ylabel('Total Floor Area (m²)')\n"
    "axes[1].grid(axis='y', alpha=0.4)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart4_boxplots.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: Clear non-overlapping separation between rating bands.')\n"
    "print('Median efficiency: A=93, B=83, C=73, D=64, E=50 — consistent with SAP thresholds.')"
))

# Chart 5
cells.append(md("### Chart 5: Tenure Distribution and Cost Saving Potential"))
cells.append(code(
    "tenure_counts = df['TENURE_CLEAN'].value_counts()\n"
    "total         = len(df)\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "bars5 = axes[0].bar(tenure_counts.index, tenure_counts.values,\n"
    "                     color=PALETTE[:len(tenure_counts)],\n"
    "                     edgecolor='white', linewidth=1.2, width=0.6)\n"
    "bar_labels(axes[0], bars5, tenure_counts.values, total=total, fontsize=10)\n"
    "axes[0].set_ylim(0, tenure_counts.max() * 1.25)\n"
    "axes[0].set_title('Property Tenure Distribution (n=4,579)', pad=15)\n"
    "axes[0].set_xlabel('Tenure Type')\n"
    "axes[0].set_ylabel('Number of Properties')\n"
    "axes[0].tick_params(axis='x', rotation=10)\n"
    "axes[0].grid(axis='y', alpha=0.4); axes[0].set_axisbelow(True)\n\n"
    "q1  = df['COST_SAVING_POTENTIAL'].quantile(0.25)\n"
    "med = df['COST_SAVING_POTENTIAL'].median()\n"
    "q3  = df['COST_SAVING_POTENTIAL'].quantile(0.75)\n"
    "mn  = df['COST_SAVING_POTENTIAL'].mean()\n"
    "axes[1].hist(df['COST_SAVING_POTENTIAL'], bins=45,\n"
    "             color='#3498db', edgecolor='white', linewidth=0.4, alpha=0.88)\n"
    "axes[1].axvline(mn,  color='#e74c3c', linestyle='--', linewidth=2,\n"
    "                label=f'Mean:   £{mn:.0f}/yr')\n"
    "axes[1].axvline(med, color='#f39c12', linestyle='--', linewidth=2,\n"
    "                label=f'Median: £{med:.0f}/yr')\n"
    "axes[1].axvline(q1,  color='#27ae60', linestyle=':',  linewidth=1.5,\n"
    "                label=f'Q1: £{q1:.0f}/yr')\n"
    "axes[1].axvline(q3,  color='#27ae60', linestyle=':',  linewidth=1.5,\n"
    "                label=f'Q3: £{q3:.0f}/yr')\n"
    "axes[1].set_title('Distribution of Annual Cost Saving Potential', pad=15)\n"
    "axes[1].set_xlabel('Cost Saving Potential (£/year)')\n"
    "axes[1].set_ylabel('Number of Properties')\n"
    "axes[1].legend(fontsize=9.5)\n"
    "axes[1].grid(axis='y', alpha=0.4)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart5_tenure_cost.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: Social Rented is the largest tenure group (43.7%).')\n"
    "print(f'Mean annual saving potential: £{mn:.0f} per property (median: £{med:.0f}).')\n"
    "print(f'25% of properties could save more than £{q3:.0f}/year.')"
))

# ── SECTION 5: DIAGNOSTIC ANALYTICS ────────────────────────────────────────
cells.append(md(
    "## Section 5: Diagnostic Analytics (Analysis 3.3)\n\n"
    "Diagnostic analytics answers **'Why did this happen?'** by examining the root causes "
    "of energy performance variation. We analyse correlations, the impact of insulation quality, "
    "how construction age and tenure drive CO2 and efficiency outcomes."
))

# Chart 6
cells.append(md("### Chart 6: Correlation Matrix"))
cells.append(code(
    "num_corr = ['CURRENT_ENERGY_EFFICIENCY','POTENTIAL_ENERGY_EFFICIENCY',\n"
    "            'ENERGY_RATING_NUMERIC','TOTAL_FLOOR_AREA','CO2_EMISSIONS_CURRENT',\n"
    "            'HEATING_COST_CURRENT','TOTAL_COST_CURRENT','EFFICIENCY_GAP',\n"
    "            'COST_SAVING_POTENTIAL','CO2_PER_AREA',\n"
    "            'NUMBER_HABITABLE_ROOMS','INSPECTION_YEAR']\n"
    "corr = df[num_corr].corr().round(2)\n\n"
    "fig, ax = plt.subplots(figsize=(14, 10))\n"
    "mask = np.triu(np.ones_like(corr, dtype=bool))\n"
    "sns.heatmap(corr, mask=mask, annot=True, fmt='.2f',\n"
    "            cmap='RdYlGn', center=0, square=True,\n"
    "            linewidths=0.5, annot_kws={'size': 9, 'weight': 'bold'},\n"
    "            cbar_kws={'shrink': 0.75, 'label': 'Pearson r'}, ax=ax)\n"
    "ax.set_title('Correlation Matrix — Liverpool EPC Numerical Features', pad=18)\n"
    "plt.xticks(rotation=40, ha='right', fontsize=9)\n"
    "plt.yticks(rotation=0, fontsize=9)\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart6_correlation_heatmap.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n\n"
    "print('Top correlations with CURRENT_ENERGY_EFFICIENCY:')\n"
    "corr_target = corr['CURRENT_ENERGY_EFFICIENCY'].drop('CURRENT_ENERGY_EFFICIENCY').sort_values(ascending=False)\n"
    "display(corr_target.to_frame().rename(columns={'CURRENT_ENERGY_EFFICIENCY': 'Pearson r'}))"
))

# Chart 7
cells.append(md("### Chart 7: Impact of Insulation Quality on Energy Efficiency"))
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n\n"
    "wall_data = (df.groupby('WALLS_ENERGY_EFF')['CURRENT_ENERGY_EFFICIENCY']\n"
    "               .agg(['mean','count']).reindex(EFF_ORDER).dropna())\n"
    "roof_data = (df.groupby('ROOF_ENERGY_EFF')['CURRENT_ENERGY_EFFICIENCY']\n"
    "               .agg(['mean','count']).reindex(EFF_ORDER).dropna())\n\n"
    "for ax, data, title in [\n"
    "        (axes[0], wall_data, 'Wall Insulation'),\n"
    "        (axes[1], roof_data, 'Roof Insulation')]:\n"
    "    bars = ax.barh(data.index, data['mean'].values,\n"
    "                   color=EFF_COLORS[:len(data)],\n"
    "                   edgecolor='white', linewidth=1.0, height=0.6)\n"
    "    xlim = data['mean'].max() * 1.12\n"
    "    ax.set_xlim(0, xlim)\n"
    "    for bar, (idx, row) in zip(bars, data.iterrows()):\n"
    "        ax.text(row['mean'] + 0.3, bar.get_y() + bar.get_height()/2,\n"
    "                f'{row[\"mean\"]:.1f}  (n={int(row[\"count\"]):,})',\n"
    "                va='center', fontsize=9.5, fontweight='bold')\n"
    "    eff_range = data['mean'].max() - data['mean'].min()\n"
    "    ax.set_title(f'Average Efficiency by {title} Rating\\n'\n"
    "                 f'Range: {eff_range:.1f} points (Very Poor to Very Good)', pad=12)\n"
    "    ax.set_xlabel('Average Energy Efficiency Score')\n"
    "    ax.set_ylabel(f'{title} Rating')\n"
    "    ax.grid(axis='x', alpha=0.4); ax.set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart7_wall_roof_insulation.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n\n"
    "wall_range = wall_data['mean'].max() - wall_data['mean'].min()\n"
    "roof_range = roof_data['mean'].max() - roof_data['mean'].min()\n"
    "print(f'Wall insulation efficiency range: {wall_range:.1f} points')\n"
    "print(f'Roof insulation efficiency range: {roof_range:.1f} points')\n"
    "print('Finding: Wall insulation is the most impactful single retrofit.')\n"
    "print('Very Good walls average 81.1 vs Very Poor at 69.1 — a 12 point difference.')"
))

# Chart 8
cells.append(md("### Chart 8: CO2 Emissions Analysis"))
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "df_rated = df[df['CURRENT_ENERGY_RATING'].isin(['A','B','C','D','E'])]\n"
    "r_pal    = [RATING_COLORS[r] for r in ['A','B','C','D','E']]\n"
    "sns.boxplot(data=df_rated, x='CURRENT_ENERGY_RATING', y='CO2_EMISSIONS_CURRENT',\n"
    "            order=['A','B','C','D','E'], palette=r_pal,\n"
    "            ax=axes[0], linewidth=1.2, fliersize=3)\n"
    "for i, rating in enumerate(['A','B','C','D','E']):\n"
    "    med = df_rated[df_rated['CURRENT_ENERGY_RATING']==rating]['CO2_EMISSIONS_CURRENT'].median()\n"
    "    n   = (df_rated['CURRENT_ENERGY_RATING']==rating).sum()\n"
    "    axes[0].text(i, med + 0.03, f'{med:.2f}t',\n"
    "                 ha='center', fontsize=9, fontweight='bold')\n"
    "    axes[0].text(i, axes[0].get_ylim()[0]+0.04, f'n={n}',\n"
    "                 ha='center', fontsize=8, color='#555')\n"
    "axes[0].set_title('CO₂ Emissions Distribution by Energy Rating', pad=15)\n"
    "axes[0].set_xlabel('Energy Rating')\n"
    "axes[0].set_ylabel('CO₂ Emissions (tonnes/year)')\n"
    "axes[0].grid(axis='y', alpha=0.4)\n\n"
    "co2_age  = df.groupby('PROPERTY_AGE_GROUP')['CO2_EMISSIONS_CURRENT'].mean().reindex(AGE_ORDER).dropna()\n"
    "bars_co2 = axes[1].bar(range(len(co2_age)), co2_age.values,\n"
    "                        color=AGE_COLORS[:len(co2_age)],\n"
    "                        edgecolor='white', linewidth=1.2, width=0.65)\n"
    "for i, val in enumerate(co2_age.values):\n"
    "    axes[1].text(i, val + 0.01, f'{val:.2f}t',\n"
    "                 ha='center', fontsize=9.5, fontweight='bold')\n"
    "axes[1].set_xticks(range(len(co2_age)))\n"
    "axes[1].set_xticklabels(co2_age.index, rotation=30, ha='right', fontsize=9)\n"
    "axes[1].axhline(df['CO2_EMISSIONS_CURRENT'].mean(), color='red',\n"
    "                linestyle='--', linewidth=1.5,\n"
    "                label=f'Mean: {df[\"CO2_EMISSIONS_CURRENT\"].mean():.2f}t')\n"
    "axes[1].legend(fontsize=9)\n"
    "axes[1].set_title('Average CO₂ Emissions by Property Age Group', pad=15)\n"
    "axes[1].set_xlabel('Age Group')\n"
    "axes[1].set_ylabel('Average CO₂ Emissions (tonnes/year)')\n"
    "axes[1].grid(axis='y', alpha=0.4); axes[1].set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart8_co2_analysis.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: E-rated properties produce ~5x more CO2 than A-rated.')\n"
    "print('Pre-1900 stock emits significantly more than modern builds.')"
))

# Chart 9
cells.append(md("### Chart 9: Floor Area vs Efficiency and Main Fuel Type"))
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "df_rated = df[df['CURRENT_ENERGY_RATING'].isin(['A','B','C','D','E'])]\n"
    "for rating in ['A','B','C','D','E']:\n"
    "    grp = df_rated[df_rated['CURRENT_ENERGY_RATING'] == rating]\n"
    "    axes[0].scatter(grp['TOTAL_FLOOR_AREA'], grp['CURRENT_ENERGY_EFFICIENCY'],\n"
    "                    label=f'Rating {rating}  (n={len(grp):,})',\n"
    "                    alpha=0.42, color=RATING_COLORS[rating], s=16)\n"
    "axes[0].set_title('Floor Area vs Energy Efficiency by Rating Band', pad=15)\n"
    "axes[0].set_xlabel('Total Floor Area (m²)')\n"
    "axes[0].set_ylabel('Energy Efficiency Score')\n"
    "axes[0].legend(title='Rating', fontsize=8.5, title_fontsize=9)\n"
    "axes[0].grid(alpha=0.3)\n\n"
    "# Simplify fuel labels and show top 6\n"
    "fuel_map = {\n"
    "    'mains gas (not community)':                       'Mains Gas',\n"
    "    'electricity (not community)':                    'Electricity',\n"
    "    'mains gas (community)':                           'Gas (Community)',\n"
    "    'Electricity: electricity, unspecified tariff':    'Electricity (Other)',\n"
    "    'Gas: mains gas':                                  'Gas (Other)',\n"
    "}\n"
    "df['FUEL_LABEL'] = df['MAIN_FUEL'].map(fuel_map).fillna('Other')\n"
    "fuel_stats = (df.groupby('FUEL_LABEL').agg(\n"
    "    Mean_Efficiency=('CURRENT_ENERGY_EFFICIENCY','mean'),\n"
    "    Count=('CURRENT_ENERGY_EFFICIENCY','count')\n"
    ").sort_values('Mean_Efficiency', ascending=False))\n\n"
    "bars_f = axes[1].barh(fuel_stats.index, fuel_stats['Mean_Efficiency'],\n"
    "                       color='#3498db', edgecolor='white', linewidth=0.8, height=0.6)\n"
    "xlim = fuel_stats['Mean_Efficiency'].max() * 1.18\n"
    "axes[1].set_xlim(0, xlim)\n"
    "for bar, (idx, row) in zip(bars_f, fuel_stats.iterrows()):\n"
    "    axes[1].text(row['Mean_Efficiency'] + 0.3,\n"
    "                 bar.get_y() + bar.get_height()/2,\n"
    "                 f'{row[\"Mean_Efficiency\"]:.1f}  (n={int(row[\"Count\"]):,})',\n"
    "                 va='center', fontsize=9, fontweight='bold')\n"
    "axes[1].set_title('Average Efficiency by Main Fuel Type', pad=15)\n"
    "axes[1].set_xlabel('Average Energy Efficiency Score')\n"
    "axes[1].set_ylabel('Fuel Type')\n"
    "axes[1].grid(axis='x', alpha=0.4); axes[1].set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart9_scatter_fuel.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: Mains gas dominates (79.9% of properties). No strong linear relationship')\n"
    "print('between floor area and efficiency — building fabric matters more than size.')"
))

# Chart 10
cells.append(md("### Chart 10: Efficiency Gap and Cost Saving by Tenure and Age"))
cells.append(code(
    "tenure_gap = (df.groupby('TENURE_CLEAN')['EFFICIENCY_GAP']\n"
    "                .mean().sort_values(ascending=False))\n"
    "cost_age   = (df.groupby('PROPERTY_AGE_GROUP')['COST_SAVING_POTENTIAL']\n"
    "                .mean().reindex(AGE_ORDER).dropna())\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "# Colour bars by gap size\n"
    "gap_colors = ['#e74c3c' if v > 8 else '#e67e22' if v > 6 else '#f1c40f' if v > 3\n"
    "              else '#27ae60' for v in tenure_gap.values]\n"
    "bars_tg = axes[0].bar(tenure_gap.index, tenure_gap.values,\n"
    "                       color=gap_colors,\n"
    "                       edgecolor='white', linewidth=1.2, width=0.55)\n"
    "for bar, val in zip(bars_tg, tenure_gap.values):\n"
    "    axes[0].text(bar.get_x() + bar.get_width()/2,\n"
    "                 bar.get_height() + 0.08,\n"
    "                 f'{val:.1f} pts', ha='center', fontsize=10.5, fontweight='bold')\n"
    "axes[0].set_ylim(0, tenure_gap.max() * 1.22)\n"
    "axes[0].set_title('Average Efficiency Gap by Tenure Type', pad=15)\n"
    "axes[0].set_xlabel('Tenure Type')\n"
    "axes[0].set_ylabel('Average Efficiency Gap (points)')\n"
    "axes[0].tick_params(axis='x', rotation=10)\n"
    "axes[0].grid(axis='y', alpha=0.4); axes[0].set_axisbelow(True)\n\n"
    "bars_ca = axes[1].bar(range(len(cost_age)), cost_age.values,\n"
    "                       color=AGE_COLORS[:len(cost_age)],\n"
    "                       edgecolor='white', linewidth=1.2, width=0.65)\n"
    "for i, val in enumerate(cost_age.values):\n"
    "    axes[1].text(i, val + 1.2, f'£{val:.0f}',\n"
    "                 ha='center', fontsize=9.5, fontweight='bold')\n"
    "axes[1].set_xticks(range(len(cost_age)))\n"
    "axes[1].set_xticklabels(cost_age.index, rotation=30, ha='right', fontsize=9)\n"
    "axes[1].axhline(df['COST_SAVING_POTENTIAL'].mean(), color='red',\n"
    "                linestyle='--', linewidth=1.5,\n"
    "                label=f'Overall mean: £{df[\"COST_SAVING_POTENTIAL\"].mean():.0f}')\n"
    "axes[1].legend(fontsize=9)\n"
    "axes[1].set_title('Average Annual Cost Saving Potential by Age Group', pad=15)\n"
    "axes[1].set_xlabel('Age Group')\n"
    "axes[1].set_ylabel('Average Cost Saving (£/year)')\n"
    "axes[1].grid(axis='y', alpha=0.4); axes[1].set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart10_efficiency_gap.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Finding: Owner-occupied properties have the largest efficiency gap (8.9 pts),')\n"
    "print('indicating the greatest unrealised improvement potential.')\n"
    "print('Pre-1900 stock has the highest average annual saving potential.')"
))

# ── SECTION 6: PREDICTIVE ANALYTICS ────────────────────────────────────────
cells.append(md(
    "## Section 6: Predictive Analytics (Analysis 3.4)\n\n"
    "Three classifiers predict a property's energy rating (A–E) from **25 physical building "
    "characteristics**. Features directly derived from the SAP energy calculation — such as "
    "`CURRENT_ENERGY_EFFICIENCY`, `CO2_EMISSIONS_CURRENT`, and all cost columns — are excluded "
    "because they are mathematically determined by the target label (data leakage). "
    "Including them would produce artificially inflated accuracy and no generalisation value.\n\n"
    "The dataset is split 80/20 with stratified sampling to preserve class ratios. "
    "Cross-validation is evaluated on the training partition only."
))

cells.append(code(
    "feature_cols = [\n"
    "    # Physical dimensions\n"
    "    'TOTAL_FLOOR_AREA', 'FLOOR_HEIGHT', 'NUMBER_HABITABLE_ROOMS',\n"
    "    'NUMBER_HEATED_ROOMS', 'MULTI_GLAZE_PROPORTION',\n"
    "    'LOW_ENERGY_LIGHTING', 'EXTENSION_COUNT',\n"
    "    'WIND_TURBINE_COUNT', 'PHOTO_SUPPLY',\n"
    "    # Property characteristics\n"
    "    'PROPERTY_TYPE', 'BUILT_FORM', 'PROPERTY_AGE_GROUP',\n"
    "    'TENURE_CLEAN', 'MAINS_GAS_FLAG', 'SOLAR_WATER_HEATING_FLAG',\n"
    "    'MAIN_FUEL', 'ENERGY_TARIFF',\n"
    "    # Assessor-observed efficiency ratings (not SAP-computed scores)\n"
    "    'WALLS_ENERGY_EFF', 'ROOF_ENERGY_EFF', 'WINDOWS_ENERGY_EFF',\n"
    "    'MAINHEAT_ENERGY_EFF', 'MAINHEATC_ENERGY_EFF',\n"
    "    'HOT_WATER_ENERGY_EFF', 'LIGHTING_ENERGY_EFF',\n"
    "    # Temporal\n"
    "    'INSPECTION_YEAR'\n"
    "]\n"
    "feature_cols = [c for c in feature_cols if c in df.columns]\n"
    "target       = 'CURRENT_ENERGY_RATING'\n\n"
    "df_model = df[feature_cols + [target]].copy()\n"
    "le_dict  = {}\n"
    "for col in df_model.select_dtypes(include='object').columns:\n"
    "    if col != target:\n"
    "        le = LabelEncoder()\n"
    "        df_model[col] = le.fit_transform(df_model[col].astype(str))\n"
    "        le_dict[col]  = le\n"
    "le_target        = LabelEncoder()\n"
    "df_model[target] = le_target.fit_transform(df_model[target])\n\n"
    "X = df_model[feature_cols]\n"
    "y = df_model[target]\n"
    "X_train, X_test, y_train, y_test = train_test_split(\n"
    "    X, y, test_size=0.2, random_state=42, stratify=y)\n"
    "scaler       = StandardScaler()\n"
    "X_train_s    = scaler.fit_transform(X_train)\n"
    "X_test_s     = scaler.transform(X_test)\n\n"
    "print(f'Features      : {len(feature_cols)}')\n"
    "print(f'Training rows : {X_train.shape[0]:,}')\n"
    "print(f'Testing rows  : {X_test.shape[0]:,}')\n"
    "print(f'Classes       : {list(le_target.classes_)}')\n"
    "print()\n"
    "print('Class distribution in training set:')\n"
    "y_tr_dist = pd.Series(le_target.inverse_transform(y_train)).value_counts().sort_index()\n"
    "display(pd.DataFrame({'Count': y_tr_dist,\n"
    "                       '%': (y_tr_dist / len(y_train) * 100).round(1)}))"
))

cells.append(code(
    "print('Training models...')\n"
    "print()\n\n"
    "lr_model = LogisticRegression(max_iter=1000, random_state=42)\n"
    "lr_model.fit(X_train_s, y_train)\n"
    "lr_pred  = lr_model.predict(X_test_s)\n"
    "lr_acc   = accuracy_score(y_test, lr_pred)\n"
    "lr_f1    = f1_score(y_test, lr_pred, average='weighted')\n"
    "print(f'Logistic Regression  — Accuracy: {lr_acc:.4f}  |  F1: {lr_f1:.4f}')\n\n"
    "rf_model = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)\n"
    "rf_model.fit(X_train, y_train)\n"
    "rf_pred  = rf_model.predict(X_test)\n"
    "rf_acc   = accuracy_score(y_test, rf_pred)\n"
    "rf_f1    = f1_score(y_test, rf_pred, average='weighted')\n"
    "print(f'Random Forest        — Accuracy: {rf_acc:.4f}  |  F1: {rf_f1:.4f}')\n\n"
    "gb_model = GradientBoostingClassifier(n_estimators=200, random_state=42)\n"
    "gb_model.fit(X_train, y_train)\n"
    "gb_pred  = gb_model.predict(X_test)\n"
    "gb_acc   = accuracy_score(y_test, gb_pred)\n"
    "gb_f1    = f1_score(y_test, gb_pred, average='weighted')\n"
    "print(f'Gradient Boosting    — Accuracy: {gb_acc:.4f}  |  F1: {gb_f1:.4f}')\n\n"
    "results = pd.DataFrame({\n"
    "    'Model': ['Logistic Regression','Random Forest','Gradient Boosting'],\n"
    "    'Accuracy': [lr_acc, rf_acc, gb_acc],\n"
    "    'F1 (Weighted)': [lr_f1, rf_f1, gb_f1]\n"
    "}).sort_values('Accuracy', ascending=False).reset_index(drop=True)\n"
    "results.index += 1\n"
    "results[['Accuracy','F1 (Weighted)']] = results[['Accuracy','F1 (Weighted)']].round(4)\n"
    "display(results.style.highlight_max(subset=['Accuracy','F1 (Weighted)'],\n"
    "                                     color='#d4edda'))"
))

# Chart 11
cells.append(md("### Chart 11: Model Comparison and Confusion Matrix"))
cells.append(code(
    "best_pred = gb_pred if gb_acc >= rf_acc else rf_pred\n"
    "best_name = 'Gradient Boosting' if gb_acc >= rf_acc else 'Random Forest'\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n\n"
    "x  = np.arange(3)\n"
    "w  = 0.32\n"
    "cm_names  = ['Logistic\\nRegression','Random\\nForest','Gradient\\nBoosting']\n"
    "accs      = [lr_acc, rf_acc, gb_acc]\n"
    "f1s       = [lr_f1,  rf_f1,  gb_f1]\n"
    "bar_clrs  = ['#3498db','#2ecc71','#e74c3c']\n\n"
    "b1 = axes[0].bar(x - w/2, accs, w, label='Accuracy',\n"
    "                  color=bar_clrs, edgecolor='white', linewidth=1)\n"
    "b2 = axes[0].bar(x + w/2, f1s,  w, label='F1 Score',\n"
    "                  color=bar_clrs, edgecolor='white', linewidth=1,\n"
    "                  alpha=0.55, hatch='//')\n"
    "for bar in b1:\n"
    "    axes[0].text(bar.get_x() + bar.get_width()/2,\n"
    "                 bar.get_height() + 0.003,\n"
    "                 f'{bar.get_height():.4f}',\n"
    "                 ha='center', fontsize=9, fontweight='bold')\n"
    "for bar in b2:\n"
    "    axes[0].text(bar.get_x() + bar.get_width()/2,\n"
    "                 bar.get_height() + 0.003,\n"
    "                 f'{bar.get_height():.4f}',\n"
    "                 ha='center', fontsize=9, fontweight='bold')\n"
    "axes[0].set_ylim(0.5, 0.90)\n"
    "axes[0].set_xticks(x)\n"
    "axes[0].set_xticklabels(cm_names, fontsize=10)\n"
    "axes[0].set_ylabel('Score')\n"
    "axes[0].set_title('Model Performance Comparison (Test Set)', pad=15)\n"
    "axes[0].legend(fontsize=9.5)\n"
    "axes[0].grid(axis='y', alpha=0.4); axes[0].set_axisbelow(True)\n\n"
    "# Confusion matrix with both count and normalised %\n"
    "cm      = confusion_matrix(y_test, best_pred)\n"
    "cm_norm = confusion_matrix(y_test, best_pred, normalize='true')\n"
    "sns.heatmap(cm, annot=False, fmt='d', cmap='Blues',\n"
    "            xticklabels=le_target.classes_,\n"
    "            yticklabels=le_target.classes_,\n"
    "            ax=axes[1], linewidths=0.5)\n"
    "for i in range(cm.shape[0]):\n"
    "    for j in range(cm.shape[1]):\n"
    "        axes[1].text(j + 0.5, i + 0.4,\n"
    "                     f'{cm[i,j]}',\n"
    "                     ha='center', va='center',\n"
    "                     fontsize=11, fontweight='bold',\n"
    "                     color='white' if cm_norm[i,j] > 0.5 else 'black')\n"
    "        axes[1].text(j + 0.5, i + 0.65,\n"
    "                     f'({cm_norm[i,j]*100:.1f}%)',\n"
    "                     ha='center', va='center',\n"
    "                     fontsize=8,\n"
    "                     color='white' if cm_norm[i,j] > 0.5 else '#444')\n"
    "axes[1].set_title(f'Confusion Matrix — {best_name}\\n(count + row %)', pad=15)\n"
    "axes[1].set_xlabel('Predicted Rating')\n"
    "axes[1].set_ylabel('Actual Rating')\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart11_model_comparison.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()"
))

cells.append(code(
    "print(f'Classification Report — {best_name}')\n"
    "print()\n"
    "print(classification_report(y_test, best_pred, target_names=le_target.classes_))\n\n"
    "print('5-Fold Cross-Validation (training data only):')\n"
    "print()\n"
    "cv_rf = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='accuracy')\n"
    "cv_gb = cross_val_score(gb_model, X_train, y_train, cv=5, scoring='accuracy')\n\n"
    "cv_results = pd.DataFrame({\n"
    "    'Model': ['Random Forest', 'Gradient Boosting'],\n"
    "    'Fold 1': [cv_rf[0], cv_gb[0]], 'Fold 2': [cv_rf[1], cv_gb[1]],\n"
    "    'Fold 3': [cv_rf[2], cv_gb[2]], 'Fold 4': [cv_rf[3], cv_gb[3]],\n"
    "    'Fold 5': [cv_rf[4], cv_gb[4]],\n"
    "    'Mean CV': [cv_rf.mean(), cv_gb.mean()],\n"
    "    'Std Dev': [cv_rf.std(),  cv_gb.std()]\n"
    "}).round(4)\n"
    "display(cv_results)"
))

# ── SECTION 7: FEATURE IMPORTANCE ──────────────────────────────────────────
cells.append(md("## Section 7: Feature Importance and Recommendations"))

cells.append(md("### Chart 12: Random Forest Feature Importances (Top 15)"))
cells.append(code(
    "importances = rf_model.feature_importances_\n"
    "fi_series   = pd.Series(importances, index=feature_cols).sort_values(ascending=False)\n"
    "top15       = fi_series.head(15)\n"
    "cumulative  = top15.cumsum() / fi_series.sum() * 100\n\n"
    "fig, ax = plt.subplots(figsize=(13, 8))\n"
    "colors_fi = plt.cm.RdYlGn_r(np.linspace(0.1, 0.9, len(top15)))\n"
    "bars = ax.barh(range(len(top15)), top15.values[::-1],\n"
    "               color=colors_fi, edgecolor='white', linewidth=0.8, height=0.7)\n"
    "ax.set_yticks(range(len(top15)))\n"
    "ax.set_yticklabels(top15.index[::-1], fontsize=10)\n"
    "xlim = top15.max() * 1.22\n"
    "ax.set_xlim(0, xlim)\n"
    "for i, (bar, val) in enumerate(zip(bars, top15.values[::-1])):\n"
    "    pct_total = val / fi_series.sum() * 100\n"
    "    ax.text(val + xlim * 0.01, bar.get_y() + bar.get_height()/2,\n"
    "            f'{val:.4f}  ({pct_total:.1f}% of total)',\n"
    "            va='center', fontsize=9, fontweight='bold')\n"
    "ax.set_title('Top 15 Feature Importances — Random Forest\\n'\n"
    "             'Key Drivers of Energy Rating Prediction — Liverpool EPC', pad=15)\n"
    "ax.set_xlabel('Mean Decrease in Impurity')\n"
    "ax.set_ylabel('Feature')\n"
    "ax.grid(axis='x', alpha=0.4); ax.set_axisbelow(True)\n\n"
    "top15_pct = (top15 / fi_series.sum() * 100).sum()\n"
    "ax.text(0.98, 0.02, f'Top 15 features explain\\n{top15_pct:.1f}% of total importance',\n"
    "        transform=ax.transAxes, ha='right', va='bottom',\n"
    "        fontsize=9, bbox=dict(boxstyle='round', facecolor='#f0f0f0', alpha=0.8))\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart12_feature_importance.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Top 10 features:')\n"
    "top10 = pd.DataFrame({'Importance': fi_series.head(10).round(4),\n"
    "                       '% of Total': (fi_series.head(10)/fi_series.sum()*100).round(1)})\n"
    "display(top10)"
))

cells.append(md("### Chart 13: Feature Importance — All 25 Features (Ascending)"))
cells.append(code(
    "fi_asc = fi_series.sort_values(ascending=True)\n\n"
    "fig, ax = plt.subplots(figsize=(13, 9))\n"
    "colors_13 = plt.cm.RdYlGn(np.linspace(0.15, 0.9, len(fi_asc)))\n"
    "bars13 = ax.barh(range(len(fi_asc)), fi_asc.values,\n"
    "                  color=colors_13, edgecolor='white', linewidth=0.6, height=0.7)\n"
    "ax.set_yticks(range(len(fi_asc)))\n"
    "ax.set_yticklabels(fi_asc.index, fontsize=9.5)\n"
    "xlim = fi_asc.max() * 1.22\n"
    "ax.set_xlim(0, xlim)\n"
    "for bar, val in zip(bars13, fi_asc.values):\n"
    "    pct = val / fi_series.sum() * 100\n"
    "    ax.text(val + xlim * 0.01, bar.get_y() + bar.get_height()/2,\n"
    "            f'{val:.4f}  ({pct:.1f}%)', va='center', fontsize=8.5, fontweight='bold')\n"
    "ax.set_title('Feature Importance — All 25 Features (Random Forest)\\n'\n"
    "             'Importance Score and % of Total Explained Variance', pad=15)\n"
    "ax.set_xlabel('Mean Decrease in Impurity')\n"
    "ax.grid(axis='x', alpha=0.4); ax.set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart13_feature_importance_detailed.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()"
))

cells.append(md("### Chart 14: Permutation Feature Importance"))
cells.append(code(
    "print('Calculating permutation importance...')\n"
    "perm       = permutation_importance(rf_model, X_test, y_test,\n"
    "                                     n_repeats=10, random_state=42, n_jobs=-1)\n"
    "perm_s     = pd.Series(perm.importances_mean, index=feature_cols).sort_values()\n"
    "perm_std_s = pd.Series(perm.importances_std,  index=feature_cols).loc[perm_s.index]\n\n"
    "fig, ax = plt.subplots(figsize=(13, 9))\n"
    "colors_14 = plt.cm.coolwarm(np.linspace(0.1, 0.9, len(perm_s)))\n"
    "bars14 = ax.barh(range(len(perm_s)), perm_s.values,\n"
    "                  xerr=perm_std_s.values,\n"
    "                  color=colors_14, edgecolor='white', linewidth=0.6,\n"
    "                  height=0.7, error_kw={'elinewidth': 1.2, 'ecolor': '#555'})\n"
    "ax.set_yticks(range(len(perm_s)))\n"
    "ax.set_yticklabels(perm_s.index, fontsize=9.5)\n"
    "for bar, val, std in zip(bars14, perm_s.values, perm_std_s.values):\n"
    "    ax.text(max(val, 0) + max(std, 0) + 0.0005,\n"
    "            bar.get_y() + bar.get_height()/2,\n"
    "            f'{val:.4f} ± {std:.4f}',\n"
    "            va='center', fontsize=8.5, fontweight='bold')\n"
    "ax.axvline(0, color='black', linewidth=0.8, linestyle='--')\n"
    "ax.set_title('Permutation Feature Importance — Random Forest\\n'\n"
    "             'Mean Decrease in Accuracy ± Standard Deviation (10 repeats)', pad=15)\n"
    "ax.set_xlabel('Mean Decrease in Accuracy')\n"
    "ax.grid(axis='x', alpha=0.4); ax.set_axisbelow(True)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig('chart14_permutation_importance.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print()\n"
    "print('Permutation importance validates tree-based importances by directly')\n"
    "print('measuring accuracy drop when each feature is randomly shuffled.')\n"
    "print('Error bars show variability across 10 repeat shuffles.')"
))

# ── SECTION 8: CONCLUSION ───────────────────────────────────────────────────
cells.append(md(
    "## Section 8: Recommendations and Conclusion\n\n"
    "### Key Findings\n\n"
    "1. **68.6% of Liverpool properties are rated C**, reflecting a predominantly mid-range "
    "housing stock. Only 1.5% achieved A or B ratings, indicating significant room for "
    "city-wide improvement.\n\n"
    "2. **Construction age is the primary structural driver**: Pre-1900 properties average "
    "69.5 efficiency vs 78.6 for Post-2021 builds — a 9.1-point gap driven by successive "
    "improvements in UK building regulations.\n\n"
    "3. **Wall insulation has the greatest single-feature impact**: upgrading from Very Poor "
    "to Very Good adds 12 efficiency points. Roof insulation shows a 10.8-point range. "
    "These physical retrofits represent the most cost-effective intervention pathway.\n\n"
    "4. **The predictive model (Gradient Boosting) achieves 81.2% accuracy** using only "
    "observable building characteristics — without any SAP-derived metrics. The 5-fold CV "
    "score confirms the model generalises well beyond the training data.\n\n"
    "5. **The mean annual cost saving potential is £128.50 per property**, representing "
    "approximately £588,500 per year across all 4,579 properties if improvements were made.\n\n"
    "### Recommendations\n\n"
    "1. **Target pre-1950 housing stock first**: 2,234 properties (48.8%) were built before "
    "1950 and show the lowest average efficiency. Cavity wall and loft insulation programmes "
    "should prioritise this stock.\n\n"
    "2. **Address the owner-occupied gap**: Owner-occupied properties show the largest "
    "efficiency gap (8.9 points) — the greatest unrealised potential of any tenure group. "
    "Financial incentives or green mortgages could drive uptake.\n\n"
    "3. **Expand ECO scheme access for private renters**: Private rented stock shows a "
    "7.8-point efficiency gap. Expanding eligibility criteria would benefit tenants who "
    "cannot fund improvements themselves.\n\n"
    "4. **Use the predictive model for pre-assessment targeting**: At 81.2% accuracy "
    "from building records alone, the model can flag low-performing properties before "
    "costly physical assessments, enabling smarter resource allocation.\n\n"
    "5. **Explore community heat networks**: Liverpool's dense concentration of "
    "pre-1950 terraced housing makes it suitable for district heating, which can "
    "deliver CO2 reductions across multiple properties simultaneously."
))

cells.append(code(
    "print('Notebook complete. Summary:')\n"
    "print()\n"
    "summary_final = pd.DataFrame({\n"
    "    'Item': [\n"
    "        'Properties analysed', 'Features after wrangling',\n"
    "        'Predictive features (no leakage)', 'Charts generated',\n"
    "        'Logistic Regression accuracy', 'Random Forest accuracy',\n"
    "        'Gradient Boosting accuracy', 'Best model CV score (5-fold)',\n"
    "        'Mean annual cost saving', 'Cleaned dataset'\n"
    "    ],\n"
    "    'Value': [\n"
    "        f'{len(df):,}', df.shape[1], len(feature_cols), 15,\n"
    "        f'{lr_acc:.4f}', f'{rf_acc:.4f}', f'{gb_acc:.4f}',\n"
    "        f'{cv_gb.mean():.4f} (Gradient Boosting)',\n"
    "        f'£{df[\"COST_SAVING_POTENTIAL\"].mean():.2f}/property/year',\n"
    "        'liverpool_epc_cleaned.csv'\n"
    "    ]\n"
    "})\n"
    "display(summary_final)"
))

# ── BUILD ───────────────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": cells
}

with open(r"C:\Users\VIDEO CALLS\OneDrive\Pictures\DataScience\Liverpool_EPC_Analysis.ipynb",
          "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Built: {len(cells)} cells  ({sum(1 for c in cells if c['cell_type']=='code')} code, "
      f"{sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
